# Site settings
title: Dockercasts
email: tim@dockercasts.co
description: >
  DockerCasts is producted by Tim Hogg.
  All screencasts center on one topic or technique that can be
  easily understood and applied to projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dockercasts.co" # the base hostname & protocol for your site
twitter_username: dockercasts
github_username:  dockercasts

# Build settings
markdown: kramdown
