# Site settings
title: Dockercasts
email: tim@dockercasts.co
description: >
  DockerCasts is producted by Tim Hogg.
  <br />
  All screencasts center on one topic or technique that can be
  easily understood and applied to projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dockercasts.co" # the base hostname & protocol for your site
twitter_username: dockercasts
github_username:  dockercasts

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true

